name: render-deploy-nest-backend

on:
  push:
    branches: class-12-deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      ##CLONE CODE
      - name: Checkout code
        uses: actions/checkout@v2

        ##UPLOAD TO DOCKER HUB

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker hub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/nestjs-backend-pt19a:latest
      ## DEPLOY TO RENDER

      - name: Deploy to render
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{secrets.RENDER_SERVICE_ID}}
          api-key: ${{secrets.RENDER_API_KEY}}
          wait-for-success: true
